# https://hub.docker.com/_/busybox https://busybox.net/
ARG ALPINE_VERSION=3.17
FROM docker.io/alpine:$ALPINE_VERSION AS build

# hadolint ignore=DL3018
RUN apk add --no-cache \
        bash \
        dash \
        coreutils \
        gzip \
        xz \
        bzip2 \
        tar \
        grep \
        sed \
        findutils \
        diffutils \
        gawk \
        procps \
        curl \
        openssl \
        openssh-client-common openssh-keygen openssh-keygen openssh-keysign \
        rsync \
        git

ENTRYPOINT ["/bin/bash"]
